# Generated by Django 2.2 on 2020-11-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='Meal',
        ),
    ]
