# Generated by Django 2.2 on 2020-11-07 20:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201105_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to=api.models.upload_to, verbose_name='Image'),
        ),
    ]
