# Generated by Django 2.2 on 2020-11-08 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_meal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='ingredients',
        ),
    ]
