# Generated by Django 2.2 on 2020-11-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_meal_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='slug',
            field=models.SlugField(default=None, max_length=250, unique='name'),
        ),
    ]
