# Generated by Django 2.2 on 2020-11-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201108_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique='name'),
        ),
    ]
