# Generated by Django 2.2 on 2020-11-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201108_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='slug',
        ),
    ]
